plugins {
    id 'groovy'
}

group = 'ru.abrosimov'
version = '1.0.0'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'org.codehaus.groovy:groovy-all:3.0.21'
}

sourceSets {
    main {
        groovy {
            srcDirs = ['src']
        }
    }
}

dependencies {
    implementation 'ru.abrosimov:jenkins-shared-lib:1.0.0'
}
